import type { FindingState } from "../contracts/domain.js";

const transitions: Readonly<Record<FindingState, readonly FindingState[]>> = {
  SIGNAL: ["HYPOTHESIS"], HYPOTHESIS: ["UNDER_REVIEW", "REJECTED"], UNDER_REVIEW: ["VALIDATION_PLANNED", "REJECTED"],
  VALIDATION_PLANNED: ["VALIDATION_BLOCKED", "PARTIALLY_VALIDATED", "CONFIRMED", "REJECTED"], VALIDATION_BLOCKED: ["VALIDATION_PLANNED", "REJECTED"],
  PARTIALLY_VALIDATED: ["VALIDATION_PLANNED", "CONFIRMED", "REJECTED"], CONFIRMED: ["ACCEPTED", "RISK_ACCEPTED", "REJECTED"], ACCEPTED: ["PATCH_PROPOSED", "RISK_ACCEPTED", "CLOSED"],
  PATCH_PROPOSED: ["FIX_VERIFIED", "CONFIRMED"], FIX_VERIFIED: ["CLOSED", "CONFIRMED"], RISK_ACCEPTED: ["CLOSED", "REOPENED"], CLOSED: ["REOPENED"], REOPENED: ["UNDER_REVIEW", "VALIDATION_PLANNED"], REJECTED: []
};

export function canTransition(from: FindingState, to: FindingState): boolean { return transitions[from].includes(to); }
